version: '3'

services:
  fillingsdb:
    image: mongo:5.0.0
    container_name: fillings-database
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db

  fillingsback:
    image: node:16.4.2
    container_name: fillings-backend
    working_dir : /home/node/app
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: bash -c "npm install && npm run dev"

volumes:
  node_modules: 
